// Espelha docs/DATABASE-SCHEMA.md (tabela daily_entries) e docs/FEATURES.md (Ecrã 1).
export const DEFAULT_ENTRY = {
  sleep_hours: '',
  sleep_bed_time: '',
  sleep_wake_time: '',
  screen_hours: '',
  screen_free_morning: false,
  screen_free_night: false,
  screen_free_meal: false,
  water_liters: '',
  exercise_done: false,
  exercise_notes: '',
  back_pain_level: '',
  food_logged: false,
  food_symptoms: '',
  bible_done: false,
  prayer_minutes: '',
  rosary_done: false,
  gratitude_items: '',
  charity_done: false,
  english_minutes: '',
  english_skill: '',
  skill_minutes: '',
  skill_notes: '',
  reading_minutes: '',
  writing_done: false,
  journal_text: '',
  meditation_minutes: '',
  betting_free: true,
  betting_urge: false,
  betting_trigger: '',
  relationship_quality_time: false,
  new_social_interaction: false,
  life_experience_done: false,
  life_experience_notes: '',
  expenses_logged: false,
  day_type: 'normal',
  day_note: '',
}

export const SECTIONS = [
  {
    id: 'saude',
    title: 'Sono, água e exercício',
    fields: [
      { key: 'sleep_hours', label: 'Horas de sono', type: 'number', step: 0.5 },
      { key: 'sleep_bed_time', label: 'Hora que foi dormir', type: 'time' },
      { key: 'sleep_wake_time', label: 'Hora que acordou', type: 'time' },
      { key: 'water_liters', label: 'Água (litros)', type: 'number', step: 0.1 },
      { key: 'exercise_done', label: 'Treinei hoje', type: 'boolean' },
      { key: 'exercise_notes', label: 'Notas do treino', type: 'text' },
      { key: 'back_pain_level', label: 'Dor lombar (0–10)', type: 'number', min: 0, max: 10 },
    ],
  },
  {
    id: 'alimentacao',
    title: 'Alimentação',
    fields: [
      { key: 'food_logged', label: 'Registei a alimentação de hoje', type: 'boolean' },
      { key: 'food_symptoms', label: 'Sintomas de gastrite percebidos', type: 'text' },
    ],
  },
  {
    id: 'espiritualidade',
    title: 'Espiritualidade',
    fields: [
      { key: 'bible_done', label: 'Li a Bíblia', type: 'boolean' },
      { key: 'prayer_minutes', label: 'Minutos de oração', type: 'number' },
      { key: 'rosary_done', label: 'Rezei o terço', type: 'boolean' },
      { key: 'gratitude_items', label: '3 coisas pelas quais sou grata', type: 'text' },
      { key: 'charity_done', label: 'Fiz um ato de caridade/serviço', type: 'boolean' },
    ],
  },
  {
    id: 'crescimento',
    title: 'Inglês, habilidade e desenvolvimento',
    fields: [
      { key: 'english_minutes', label: 'Minutos de inglês', type: 'number' },
      {
        key: 'english_skill',
        label: 'Foco do inglês hoje',
        type: 'select',
        options: ['', 'listening', 'reading', 'vocabulary', 'writing', 'speaking'],
      },
      { key: 'skill_minutes', label: 'Minutos na habilidade profissional', type: 'number' },
      { key: 'skill_notes', label: 'O que fiz na habilidade', type: 'text' },
      { key: 'reading_minutes', label: 'Minutos de leitura', type: 'number' },
      { key: 'writing_done', label: 'Escrevi / journaling', type: 'boolean' },
      { key: 'journal_text', label: 'Texto livre do dia (opcional)', type: 'textarea' },
      { key: 'meditation_minutes', label: 'Minutos de meditação', type: 'number' },
    ],
  },
  {
    id: 'digital',
    title: 'Disciplina digital',
    fields: [
      { key: 'screen_hours', label: 'Horas de tela', type: 'number', step: 0.5 },
      { key: 'screen_free_morning', label: '30 min sem redes ao acordar', type: 'boolean' },
      { key: 'screen_free_night', label: '30 min sem redes antes de dormir', type: 'boolean' },
      { key: 'screen_free_meal', label: '1 refeição sem celular', type: 'boolean' },
    ],
  },
  {
    id: 'apostas',
    title: 'Apostas',
    fields: [
      { key: 'betting_free', label: 'Não apostei hoje', type: 'boolean', highlight: true },
      { key: 'betting_urge', label: 'Senti vontade forte de apostar', type: 'boolean' },
      { key: 'betting_trigger', label: 'Gatilho identificado (se houve vontade)', type: 'text' },
    ],
  },
  {
    id: 'relacoes',
    title: 'Relacionamento e vida social',
    fields: [
      { key: 'relationship_quality_time', label: 'Momento de qualidade com a namorada', type: 'boolean' },
      { key: 'new_social_interaction', label: 'Nova conversa / interação social', type: 'boolean' },
      { key: 'life_experience_done', label: 'Experiência significativa da semana', type: 'boolean' },
      { key: 'life_experience_notes', label: 'O que foi', type: 'text' },
    ],
  },
  {
    id: 'financas',
    title: 'Finanças',
    fields: [
      { key: 'expenses_logged', label: 'Registei os gastos de hoje', type: 'boolean' },
    ],
  },
  {
    id: 'fechamento',
    title: 'Fechamento do dia',
    fields: [
      {
        key: 'day_type',
        label: 'Tipo de dia',
        type: 'select',
        options: ['normal', 'corrido', 'ruim'],
      },
      { key: 'day_note', label: 'Nota do dia', type: 'textarea' },
    ],
  },
]
